# Generated by Django 5.1.5 on 2025-07-30 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='softwareKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('software_info', models.TextField(null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='static/softwarethumb/')),
                ('download_link', models.CharField(max_length=200, null=True)),
                ('posted_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/category')),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.batch')),
            ],
        ),
    ]
