# Generated by Django 5.1.5 on 2025-08-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_softwarekit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/category/'),
        ),
        migrations.AlterField(
            model_name='tblregister',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.batch'),
        ),
    ]
