# Generated by Django 5.1.5 on 2025-08-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_mylecture_mytask_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(blank=True, null=True, upload_to='static/notes/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/Category/'),
        ),
    ]
